version: 2.0.0-{build}

branches:
  except:
    - doc

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\BearLibTerminal.rs

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin;C:\
  - set LIBRARY_PATH=C:\
  -
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu"
  -
  - git clone https://github.com/nabijaczleweli/BearLibTerminal.git C:\BearLibTerminal
  - cd C:\BearLibTerminal\Build
  - cmake -G"MSYS Makefiles" ..
  - make BearLibTerminal
  - copy ..\Output\Windows64\BearLibTerminal.dll C:\
  - cd C:\BearLibTerminal.rs
  - copy C:\BearLibTerminal.dll .

build: off
build_script:
  - cargo build --verbose

test: off
test_script:
  - cargo test --verbose

artifacts:
  - path: BearLibTerminal.dll

deploy:
  provider: GitHub
  artifact: BearLibTerminal.dll
  auth_token:
    secure: hPYB/rvXWxVoVXCjw8GYOCfF/5VAfCcHm7q1sNz/dajIov0KeXjiB7QW8O3T2w1r
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
